version: '3.8'

services:
  api:
    build: .
    image: wimi-backend:${APP_VERSION:-latest}
    ports:
      - "${PORT:-8000}:8000"
    env_file:
      - .env
    environment:
      - ENVIRONMENT=production
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4 --proxy-headers
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M 